### PR TITLE
Remove AuthSession from the Seed 

### LINKED ISSUE #38: Remove the Unused AuthSession Creation in the Seeds
- I believe we should remove `AuthSession` creation from the `seeds.rb` because we are creating it with the dummy credentials and it fails to create it 
- Due to its failure, we are not creating the `Movement` data afterward.
- Moreover, I believe it's not being used in the `seeds.rb` as well, so no harm in removing it. After all, we are just creating the test data in the seeds.rb

### PR DESCRIPTION
**Pull request by chahmedejaz**
Resolves #38 

- This PR removes the `AuthSession` creation from the seeds
- Due to the invalid creds in .env file, the `db:seed` always gets failed
- Moreover, we are setting the `external_account_id` for the seeded account. So, we can bypass the creation of the test `AuthSession` which when successfully created, sets `external_account_id`

Please let me know if I'm missing anything. Thanks.

### CODE REVIEW

File: db/seeds.rb [hunk 1]
```diff
@@ -23,12 +23,6 @@
   institution_id: institution.id,
   external_account_id: "48883f05-bfe1-46fb-818c-d272ace6a069")
 
-AuthSession.create!(account: account,
```
Comment (EduardoSimon) [inline db/seeds.rb:26]: I was thinking that instead of just removing its creation we could leave one in a pending state and another one in a successful state. How about something like this?

```
institution = Institution.create!(name: "local institution",
                                  institution_id: "local_institution_1",
                                  thumbnail_url: "https://picsum.photos/200")

account = Account.create!(name: "Unlinked account DO NOT SYNC",
  budget: budget,
  institution_id: institution.id,
  external_account_id: "48883f05-bfe1-46fb-818c-d272ace6a069")

account_to_be_linked = Account.create!(name: "Account to be linked",
  budget: budget,
  institution_id: institution.id,
  external_account_id: nil)

AuthSession.create!(account: account,
  external_id: "707bbbe7-12e3-41e9-98f9-23277b1fb186",
  status: "success",
  external_account_id: "wadus",
  external_institution_id: institution.institution_id)

AuthSession.create!(account: account_to_be_linked,
  external_id: "707bbbe7-12e3-41e9-98f9-23277b1",
  status: "in_progress",
  external_account_id: nil,
  external_institution_id: "SANDBOXFINANCE_SFIN0000")

```

File: README.md [hunk 2]
```diff
@@ -33,6 +33,8 @@ Use a ruby dependency manager like rbenv or asdf. The supported ruby version is
 
 `bin/rails s`
 
+**Note:** It's important to replace your valid GoCardless credentials in the .env file to fully leverage the application's functionalities.
```
Comment (EduardoSimon) [inline README.md:36]: I would avoid recommending to overwrite the .env file as that's committed and a hypothetical developer could leak its gocardless credentials. According to `rails-dotenv` documentation the right approach would be to create an ignored file named: `env.local.development`

How about also linking this [table](https://github.com/bkeepers/dotenv#what-other-env-files-can-i-use) in the README?

**Review by EduardoSimon — CHANGES_REQUESTED** [review]

File: db/seeds.rb (hunk 1 above)
Comment (chahmedejaz) [reply db/seeds.rb:26]: If we do this, then we are back to the square one😅
The reason is this callback:
https://github.com/EduardoSimon/budget.io/blob/main/app/models/auth_session.rb#L4

This calls the GoCardless API and then authentication fails during the seed phase.

Sorry if I'm missing anything, but I'm not able to see why do we need an AuthSession object in the seeds?😅 I don't think they are needed when we already have created accounts with external_account_id. 

If we really need these, then we should create it by skipping the `before_create` callbacks.

File: README.md (hunk 2 above)
Comment (chahmedejaz) [reply README.md:36]: Sure, will update it as per this.

File: db/seeds.rb (hunk 1 above)
Comment (EduardoSimon) [reply db/seeds.rb:26]: Nope, you are not missing anything. The thing is that I would like to have at least a ready-to-be-authenticated account when seeding the database for later usage. So how about if we disable the creation hook? BTW I have modified the seeds.rb file as part of #35, but it was just to make all the setup work. Feel free to modify it in this MR, but first please rebase my changes.

Comment (chahmedejaz) [reply db/seeds.rb:26]: Sure👍🏻, thanks for the heads-up otherwise I'd have conflicts 😂

**Comment by chahmedejaz** [comment]
Hey @EduardoSimon , I've addressed the comments. Please review. Thanks :)

File: test/models/auth_session_test.rb [hunk 3]
```diff
@@ -112,6 +112,18 @@ def setup
 
       @connector_mock.verify
     end
+
+    test "raises an error due to invalid creds" do
+      assert_raises(Exception) do
```
Comment (chahmedejaz) [inline test/models/auth_session_test.rb:117]: API throws the `Exception` class error on failure

Comment (EduardoSimon) [reply test/models/auth_session_test.rb:117]: Should we assert a more specific error? It could break the test suite in the future if Rails maintainers decide to change the error format but at least we are asserting correctly that the raised exception is the one from the on creation hook.

Comment (chahmedejaz) [reply test/models/auth_session_test.rb:117]: I had the same thought, that's why I tried to be as specific as possible here:
https://github.com/EduardoSimon/budget.io/blob/b098589f7938774b3d8671e6f2245b77c5502c95/test/models/auth_session_test.rb#L116-L136

However, I saw in the test suite we don't have any env set for the credentials:
image

That's why I came up with this test. We could assert with the more specific error but API only raises an error of Exception class.
What do you suggest?

Comment (chahmedejaz) [reply test/models/auth_session_test.rb:117]: Maybe mocking the API call and manually raise a `StandardError` in the mocked call with the message which the API throws for the invalid creds?

Comment (EduardoSimon) [reply test/models/auth_session_test.rb:117]: Agreed, we should mock that API call, could you please do that?

Comment (chahmedejaz) [reply test/models/auth_session_test.rb:117]: Sure, let me do that and get back to you👍🏻

**Comment by chahmedejaz** [comment]
Hey @EduardoSimon, I've mocked the method. Please review :)

**Review by EduardoSimon — APPROVED** [review]
